{{- if .Values.collectionSetup.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: collection-setup-{{ $.Release.Name }}
  labels:
    app: collection-setup-{{ $.Release.Name }}
spec:
  template:
    metadata:
      labels:
        app: collection-setup-{{ $.Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: collectionsetup
          image: {{ .Values.collectionSetup.image.name }}:{{ .Values.collectionSetup.image.tag }}
          command: {{- toYaml .Values.collectionSetup.command | nindent 12 }}
          args:
            {{- toYaml .Values.collectionSetup.args | nindent 12 }}
          ports:
            - containerPort: 5432
          resources:
            {{- toYaml .Values.collectionSetup.settings.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /opt/initdb/sql-data
              name: initdb-sql-volume-{{ $.Release.Name }}
            - mountPath: /opt/initdb/json-data
              name: initdb-json-volume-{{ $.Release.Name }}
            - mountPath: /opt/initdb/
              name: initdb-sh-volume-{{ $.Release.Name }}
          env:
            - name: PGADMIN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.collectionSetup.settings.eoapiReleaseName }}-pguser-postgres
                  key: uri
      volumes:
        - name: initdb-sql-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-sql-config-{{ $.Release.Name }}
        - name: initdb-json-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-json-config-{{ $.Release.Name }}
        - name: initdb-sh-volume-{{ $.Release.Name }}
          configMap:
            name: initdb-sh-config-{{ $.Release.Name }}
      {{- with .Values.collectionSetup.settings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.collectionSetup.settings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 1
{{- end }}