
common:
  image:
    name: ghcr.io/stac-utils/pgstac
    tag: v0.9.2
  eoapiReleaseName: eoapi
  resources:
    requests:
      cpu: "512m"
      memory: "1024Mi"
    limits:
      cpu: "512m"
      memory: "1024Mi"

load_collections:
  enabled: true
  command:
    - "sh"
  args:
    - "/opt/initdb/run-load-collections.sh"

update_collection_extents:
  enabled: true
  # 30 minutes past the hour, every 12 hours
  schedule: "30 */12 * * *"
  command:
    - "sh"
  args:
    - "-c"
    - "psql $PGADMIN_URI -f /opt/sql/update-collection-extent.sql"

run_queued_queries:
  enabled: true
  # every hour
  schedule: "0 * * * *"
  command:
    - "sh"
  args:
    - "-c"
    - "psql $PGADMIN_URI -f /opt/sql/run-queued-queries.sql"